defmodule KlassHero.Family.Adapters.Driven.Persistence.Mappers.ChildMapper do
  @moduledoc """
  Bidirectional mapping between Child domain entities and ChildSchema.

  Handles conversion between domain representation (string UUIDs) and
  database representation (binary UUIDs), ensuring clean separation
  between domain and infrastructure layers.

  ## Conversion Rules

  - Domain uses string UUIDs, schema uses binary UUIDs
  - All conversions are lossless and bidirectional
  - Nil values are handled explicitly in both directions
  """

  alias KlassHero.Family.Adapters.Driven.Persistence.Schemas.ChildSchema
  alias KlassHero.Family.Domain.Models.Child

  require Logger

  @doc """
  Converts a ChildSchema (from database) to a Child domain entity.

  Routes construction through the domain model's `from_persistence/1`
  to enforce `@enforce_keys` invariants. Raises on corrupted data.
  """
  def to_domain(%ChildSchema{} = schema) do
    attrs = %{
      id: Ecto.UUID.cast!(schema.id),
      parent_id: Ecto.UUID.cast!(schema.parent_id),
      first_name: schema.first_name,
      last_name: schema.last_name,
      date_of_birth: schema.date_of_birth,
      gender: schema.gender,
      school_grade: schema.school_grade,
      emergency_contact: schema.emergency_contact,
      support_needs: schema.support_needs,
      allergies: schema.allergies,
      school_name: schema.school_name,
      inserted_at: schema.inserted_at,
      updated_at: schema.updated_at
    }

    case Child.from_persistence(attrs) do
      {:ok, child} ->
        child

      {:error, :invalid_persistence_data} ->
        Logger.error("[ChildMapper] Corrupted persistence data",
          child_id: schema.id,
          fields: Map.keys(attrs)
        )

        raise "Corrupted child data for id=#{inspect(schema.id)} — required keys missing from persistence"
    end
  end

  @doc """
  Converts a Child domain entity to a map for ChildSchema changeset.

  Returns a map (not a schema struct) to be used with `ChildSchema.changeset/2`.
  Does not include the `id` field as it will be autogenerated on insert.
  """
  def to_schema(%Child{} = child) do
    %{
      parent_id: parse_uuid(child.parent_id),
      first_name: child.first_name,
      last_name: child.last_name,
      date_of_birth: child.date_of_birth,
      gender: child.gender,
      school_grade: child.school_grade,
      emergency_contact: child.emergency_contact,
      support_needs: child.support_needs,
      allergies: child.allergies,
      school_name: child.school_name
    }
  end

  @doc """
  Converts a list of ChildSchema records to Child domain entities.
  """
  def to_domain_list(schemas) when is_list(schemas) do
    Enum.map(schemas, &to_domain/1)
  end

  defp parse_uuid(uuid_string) when is_binary(uuid_string) do
    case Ecto.UUID.dump(uuid_string) do
      {:ok, binary} -> binary
      :error -> uuid_string
    end
  end

  defp parse_uuid(other), do: other
end
