defmodule PrimeYouth.Family.Adapters.Driven.Persistence.Mappers.ChildMapper do
  @moduledoc """
  Bidirectional mapping between Child domain entities and ChildSchema.

  Handles conversion between domain representation (string UUIDs) and
  database representation (binary UUIDs), ensuring clean separation
  between domain and infrastructure layers.

  ## Conversion Rules

  - Domain uses string UUIDs, schema uses binary UUIDs
  - All conversions are lossless and bidirectional
  - Nil values are handled explicitly in both directions
  """

  alias PrimeYouth.Family.Adapters.Driven.Persistence.Schemas.ChildSchema
  alias PrimeYouth.Family.Domain.Models.Child

  @doc """
  Converts a ChildSchema (from database) to a Child domain entity.

  ## Examples

      iex> schema = %ChildSchema{
      ...>   id: <<123, 45, 67>>,
      ...>   parent_id: <<98, 76, 54>>,
      ...>   first_name: "Alice",
      ...>   last_name: "Smith",
      ...>   date_of_birth: ~D[2018-06-15],
      ...>   notes: "Loves soccer"
      ...> }
      iex> child = to_domain(schema)
      iex> is_binary(child.id) and is_binary(child.parent_id)
      true
  """
  def to_domain(%ChildSchema{} = schema) do
    %Child{
      id: Ecto.UUID.cast!(schema.id),
      parent_id: Ecto.UUID.cast!(schema.parent_id),
      first_name: schema.first_name,
      last_name: schema.last_name,
      date_of_birth: schema.date_of_birth,
      notes: schema.notes,
      inserted_at: schema.inserted_at,
      updated_at: schema.updated_at
    }
  end

  @doc """
  Converts a Child domain entity to a map for ChildSchema changeset.

  Returns a map (not a schema struct) to be used with `ChildSchema.changeset/2`.
  Does not include the `id` field as it will be autogenerated on insert.

  ## Examples

      iex> child = %Child{
      ...>   id: "550e8400-e29b-41d4-a716-446655440000",
      ...>   parent_id: "660e8400-e29b-41d4-a716-446655440000",
      ...>   first_name: "Alice",
      ...>   last_name: "Smith",
      ...>   date_of_birth: ~D[2018-06-15],
      ...>   notes: nil
      ...> }
      iex> attrs = to_schema(child)
      iex> Map.has_key?(attrs, :parent_id)
      true
  """
  def to_schema(%Child{} = child) do
    %{
      parent_id: parse_uuid(child.parent_id),
      first_name: child.first_name,
      last_name: child.last_name,
      date_of_birth: child.date_of_birth,
      notes: child.notes
    }
  end

  @doc """
  Converts a list of ChildSchema records to Child domain entities.

  ## Examples

      iex> schemas = [%ChildSchema{...}, %ChildSchema{...}]
      iex> children = to_domain_list(schemas)
      iex> Enum.all?(children, &match?(%Child{}, &1))
      true
  """
  def to_domain_list(schemas) when is_list(schemas) do
    Enum.map(schemas, &to_domain/1)
  end

  defp parse_uuid(uuid_string) when is_binary(uuid_string) do
    case Ecto.UUID.dump(uuid_string) do
      {:ok, binary} -> binary
      :error -> uuid_string
    end
  end

  defp parse_uuid(other), do: other
end
