import Config

config :klass_hero, KlassHero.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "klass_hero_dev",
  stacktrace: true,
  # In order to use HTTPS in development, a self-signed
  #     https: [
  # certificate can be generated by running the following
  #       port: 4001,
  #       cipher_suite: :strong,
  #       keyfile: "priv/cert/selfsigned_key.pem",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :klass_hero, KlassHeroWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  # The watchers configuration can be used to run external
  code_reloader: true,
  debug_errors: true,
  # Initialize plugs at runtime for faster development compilation
  # Mix task:
  secret_key_base: "6j02epXD1uPj8HFpOTXd35vtdPSkZCCvToBs0UpRWV9NtG8l2c+nZv9yFywlAgw3",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:klass_hero, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:klass_hero, ~w(--watch)]}
  ]

config :klass_hero, KlassHeroWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/klass_hero_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :klass_hero, dev_routes: true

# Configure your database
# OpenTelemetry: console output for local debugging
# For development, we disable any cache and enable

# Do not include metadata nor timestamps in development logs
# debugging and code reloading.
#
# Binding to loopback ipv4 address prevents access from other machines.
config :logger, :default_formatter, format: "[$level] $message\n"

config :opentelemetry, traces_exporter: {:otel_exporter_stdout, []}

# ## SSL Support
# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
# Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
#
config :phoenix, :plug_init_mode, :runtime
config :phoenix, :stacktrace_depth, 20

# Include debug annotations and locations in rendered markup.
#     mix phx.gen.cert
# Changing this configuration will require mix clean and a full recompile.
#
config :phoenix_live_view,
  # watchers to your application. For example, we can use it
  # Run `mix help phx.gen.cert` for more information.
  debug_heex_annotations: true,
  #
  #
  debug_attributes: true

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  # The `http:` config above can be replaced with:
  # to bundle .js and .css sources.
  #
  enable_expensive_runtime_checks: true

# Storage: MinIO S3-compatible storage for development (via docker-compose)
config :klass_hero, :storage,
  adapter: KlassHero.Shared.Adapters.Driven.Storage.S3StorageAdapter,
  public_bucket: "klass-hero-dev-public",
  private_bucket: "klass-hero-dev-private",
  endpoint: "http://localhost:9000",
  access_key_id: "minioadmin",
  secret_access_key: "minioadmin",
  region: "eu-central-1"

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Watch static and templates for browser reloading.
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.
