defmodule KlassHero.Family.Domain.Ports.ForStoringConsents do
  @moduledoc """
  Port for consent persistence operations in the Family bounded context.

  Defines the contract for storing and querying parental consents without
  exposing infrastructure details. Implementations will be provided by
  repository adapters.

  ## Expected Return Values

  - `grant/1` - Returns `{:ok, Consent.t()}` or `{:error, changeset}`
  - `withdraw/1` - Returns `{:ok, Consent.t()}` or `{:error, :not_found}`
  - `get_active_for_child/2` - Returns `{:ok, Consent.t()}` or `{:error, :not_found}`
  - `list_active_by_child/1` - Returns list of consents directly

  Infrastructure errors (connection, query) are not caught - they crash and
  are handled by the supervision tree.
  """

  alias KlassHero.Family.Domain.Models.Consent

  @doc """
  Grants a new consent record.

  Returns:
  - `{:ok, Consent.t()}` - Consent granted successfully
  - `{:error, :already_active}` - Active consent already exists for this child+type
  - `{:error, changeset}` - Validation failed
  """
  @callback grant(map()) ::
              {:ok, Consent.t()} | {:error, :already_active} | {:error, Ecto.Changeset.t()}

  @doc """
  Withdraws a consent record by persisting the given withdrawn_at timestamp.

  The timestamp is generated by the domain model and passed through the use case,
  keeping business logic out of the persistence layer.

  Returns:
  - `{:ok, Consent.t()}` - Consent withdrawn successfully
  - `{:error, :not_found}` - Consent ID doesn't exist
  - `{:error, changeset}` - Update failed
  """
  @callback withdraw(binary(), DateTime.t()) ::
              {:ok, Consent.t()} | {:error, :not_found} | {:error, Ecto.Changeset.t()}

  @doc """
  Retrieves the active consent for a child and consent type.

  Active means withdrawn_at is nil.

  Returns:
  - `{:ok, Consent.t()}` - Active consent found
  - `{:error, :not_found}` - No active consent exists
  """
  @callback get_active_for_child(binary(), String.t()) ::
              {:ok, Consent.t()} | {:error, :not_found}

  @doc """
  Lists all active consents for a given child.

  Returns list of consents (may be empty).
  """
  @callback list_active_by_child(binary()) :: [Consent.t()]

  @doc """
  Lists active consents of a specific type for multiple children.

  Returns list of consents where child_id is in the given list and consent_type matches.
  Used for batch consent checking across multiple children.
  """
  @callback list_active_for_children([binary()], String.t()) :: [Consent.t()]

  @doc """
  Lists all consents (including withdrawn) for a given child.

  Used for GDPR data export where full audit history is required.
  Returns list of consents ordered by consent_type asc, granted_at desc.
  """
  @callback list_all_by_child(binary()) :: [Consent.t()]

  @doc """
  Deletes all consent records for a given child.

  Used during child deletion to satisfy FK constraints.

  Returns:
  - `{:ok, count}` - Number of consent records deleted
  """
  @callback delete_all_for_child(binary()) :: {:ok, non_neg_integer()}
end
