defmodule KlassHero.Family.Domain.Ports.ForStoringConsents do
  @moduledoc """
  Write-only port for consent persistence operations in the Family bounded context.

  Read operations have been moved to `ForQueryingConsents`.

  ## Expected Return Values

  - `grant/1` - Returns `{:ok, Consent.t()}` or `{:error, changeset}`
  - `withdraw/2` - Returns `{:ok, Consent.t()}` or `{:error, :not_found}`
  - `delete_all_for_child/1` - Returns `{:ok, count}`

  Infrastructure errors (connection, query) are not caught - they crash and
  are handled by the supervision tree.
  """

  alias KlassHero.Family.Domain.Models.Consent

  @doc """
  Grants a new consent record.

  Returns:
  - `{:ok, Consent.t()}` - Consent granted successfully
  - `{:error, :already_active}` - Active consent already exists for this child+type
  - `{:error, changeset}` - Validation failed
  """
  @callback grant(map()) ::
              {:ok, Consent.t()} | {:error, :already_active} | {:error, Ecto.Changeset.t()}

  @doc """
  Withdraws a consent record by persisting the given withdrawn_at timestamp.

  The timestamp is generated by the domain model and passed through the use case,
  keeping business logic out of the persistence layer.

  Returns:
  - `{:ok, Consent.t()}` - Consent withdrawn successfully
  - `{:error, :not_found}` - Consent ID doesn't exist
  - `{:error, changeset}` - Update failed
  """
  @callback withdraw(binary(), DateTime.t()) ::
              {:ok, Consent.t()} | {:error, :not_found} | {:error, Ecto.Changeset.t()}

  @doc """
  Deletes all consent records for a given child.

  Used during child deletion to satisfy FK constraints.

  Returns:
  - `{:ok, count}` - Number of consent records deleted
  """
  @callback delete_all_for_child(binary()) :: {:ok, non_neg_integer()}
end
